"use client";

import { useEffect, useRef, useState } from "react";
import { AppShell } from "./app-shell";
import { useLanguage } from "./language-provider";
import { useStudyData } from "@/hooks/use-study-data";
import { advanceBreathing, breathingModes, initialBreathingState, patternDuration, type BreathingMode, type BreathingState } from "@/lib/breathing";

type Step = "select" | "intro" | "countdown" | "breathing" | "complete";
const modes = Object.entries(breathingModes) as [BreathingMode, (typeof breathingModes)[BreathingMode]][];

export function BreathingPage() {
  const data = useStudyData(); const { messages: t } = useLanguage();
  const [mode, setMode] = useState<BreathingMode>("start"); const [groups, setGroups] = useState<1 | 2 | 3>(1); const [step, setStep] = useState<Step>("select"); const [countdown, setCountdown] = useState(3);
  const [state, setState] = useState<BreathingState>(() => initialBreathingState(breathingModes.start.pattern)); const startedAt = useRef<string | null>(null); const recorded = useRef(false); const selected = breathingModes[mode];
  useEffect(() => { if (step !== "countdown") return; const id = window.setTimeout(() => countdown > 0 ? setCountdown((v) => v - 1) : setStep("breathing"), countdown === 0 ? 450 : 1000); return () => window.clearTimeout(id); }, [countdown, step]);
  useEffect(() => { if (step !== "breathing" || state.stage === "ready") return; const id = window.setTimeout(() => setState((v) => advanceBreathing(v, selected.pattern, groups)), state.secondsRemaining === 0 ? 400 : 1000); return () => window.clearTimeout(id); }, [groups, selected.pattern, state, step]);
  useEffect(() => { if (step !== "breathing" || state.stage !== "ready" || recorded.current || !startedAt.current) return; recorded.current = true; data.recordBreath({ id: crypto.randomUUID(), mode, startedAt: startedAt.current, durationSeconds: patternDuration(selected.pattern, groups), groups }); setStep("complete"); }, [data, groups, mode, selected.pattern, state.stage, step]);
  if (!data.ready) return null;
  const phase = { inhale: t.breathing.inhale, holdIn: t.breathing.holdIn, exhale: t.breathing.exhale, holdOut: t.breathing.holdOut, ready: t.breathing.ready } as const;
  const pattern = `${t.breathing.inhale} ${selected.pattern.inhale}s · ${t.breathing.holdIn} ${selected.pattern.holdIn}s · ${t.breathing.exhale} ${selected.pattern.exhale}s · ${t.breathing.holdOut} ${selected.pattern.holdOut}s`;
  const begin = () => { startedAt.current = new Date().toISOString(); recorded.current = false; setState(initialBreathingState(selected.pattern)); setCountdown(3); setStep("countdown"); };
  const reset = () => { startedAt.current = null; recorded.current = false; setStep("select"); };
  return <AppShell settings={data.settings}><section className="mx-auto max-w-2xl py-16 sm:py-24">
    {step === "select" && <><p className="text-xs font-semibold tracking-[.14em] text-[#7B7B73]">{t.breathing.eyebrow}</p><h1 className="mt-4 font-display text-5xl tracking-[-.06em] sm:text-6xl">{t.breathing.title}</h1><div className="mt-12 grid gap-3 sm:grid-cols-2">{modes.map(([id, item]) => <button key={id} onClick={() => setMode(id)} className={`rounded-[22px] p-5 text-left transition ${mode === id ? "bg-ink text-white shadow-button" : "bg-white shadow-card hover:-translate-y-0.5"}`}><p className="font-semibold">{item.label}{id === "start" ? ` ${t.breathing.default}` : ""}</p><p className={`mt-2 text-sm ${mode === id ? "text-white/70" : "text-[#77776f]"}`}>{item.description}</p><p className={`mt-4 text-xs ${mode === id ? "text-white/60" : "text-[#88887f]"}`}>{item.pattern.inhale}-{item.pattern.holdIn}-{item.pattern.exhale}-{item.pattern.holdOut}</p></button>)}</div><div className="mt-8 rounded-[25px] bg-white p-6 shadow-card"><p className="text-sm font-semibold">{t.breathing.groups}</p><div className="mt-4 flex gap-2">{([1, 2, 3] as const).map((value) => <button key={value} onClick={() => setGroups(value)} className={`rounded-full px-4 py-2 text-sm ${groups === value ? "bg-ink text-white" : "bg-[#f0f0eb]"}`}>{value} {t.breathing.group}</button>)}</div><p className="mt-5 text-sm leading-relaxed text-[#77776f]">{t.breathing.perGroup} {pattern}</p><p className="mt-2 text-xs text-[#919189]">{t.breathing.estimated.replace("{seconds}", String(patternDuration(selected.pattern, groups)))}</p><button onClick={() => setStep("intro")} className="mt-7 rounded-full bg-ink px-6 py-3 text-sm font-semibold text-white">{t.breathing.enter}</button></div></>}
    {step === "intro" && <Centered t={t.breathing} title={t.breathing.title} subtitle={t.breathing.intro}><p className="mt-6 text-sm text-[#77776f]">{groups} {t.breathing.group} · {pattern}</p><button onClick={begin} className="mt-10 rounded-full bg-ink px-7 py-4 text-sm font-semibold text-white">{t.breathing.begin}</button></Centered>}
    {step === "countdown" && <Centered t={t.breathing} title={countdown === 0 ? t.breathing.start : t.breathing.prepare} subtitle={t.breathing.return}><p className="mt-8 font-display text-[clamp(5rem,17vw,10rem)] leading-none tracking-[-.07em] tabular-nums">{countdown}</p></Centered>}
    {step === "breathing" && state.stage !== "ready" && <Centered t={t.breathing} title={`${selected.label} · ${state.group} / ${groups}`} subtitle={pattern}><div className="mt-8 flex flex-col items-center"><p className="whitespace-nowrap px-3 font-display text-[clamp(2.25rem,8vw,4.25rem)] leading-none tracking-[-.05em]">{phase[state.stage]}</p><p className="mt-3 font-display text-[clamp(5rem,17vw,10rem)] leading-none tracking-[-.07em] tabular-nums">{state.secondsRemaining}</p></div></Centered>}
    {step === "complete" && <Centered t={t.breathing} title={t.breathing.completeTitle} subtitle={t.breathing.completeText}><button onClick={reset} className="mt-10 rounded-full bg-ink px-7 py-4 text-sm font-semibold text-white">{t.breathing.done}</button></Centered>}
  </section></AppShell>;
}
function Centered({ t, title, subtitle, children }: { t: { gentle: string }; title: string; subtitle: string; children: React.ReactNode }) { return <div className="mx-auto flex min-h-[60vh] max-w-xl flex-col justify-center text-center"><p className="text-xs font-semibold tracking-[.14em] text-[#7B7B73]">{t.gentle}</p><h1 className="mt-5 font-display text-5xl tracking-[-.06em] sm:text-6xl">{title}</h1><p className="mx-auto mt-5 max-w-md leading-relaxed text-[#6B6B63]">{subtitle}</p>{children}</div>; }
