"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "./app-shell";
import { useLanguage } from "./language-provider";
import { useStudyData } from "@/hooks/use-study-data";
import { firstPilotCore, type UserProfile } from "@/src/core";
export function SettingsPage() {
  const data = useStudyData(); const router = useRouter(); const { messages: t } = useLanguage(); const [draft, setDraft] = useState<UserProfile | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { if (data.ready) setDraft(data.settings); }, [data.ready, data.settings]);
  if (!data.ready || !draft) return null;
  const update = (changes: Partial<UserProfile>) => { setDraft((v) => v ? { ...v, ...changes } : v); setNotice(""); };
  const changed = JSON.stringify(draft) !== JSON.stringify(data.settings); const s = t.settings;
  return <AppShell settings={data.settings}><section className="mx-auto max-w-2xl py-12 sm:py-20"><p className="text-xs font-semibold tracking-[.16em] text-[#7B7B73]">FIRSTPILOT</p><h1 className="mt-3 font-display text-5xl tracking-[-.06em] sm:text-6xl">{s.title}</h1><p className="mt-4 max-w-lg text-sm leading-relaxed text-[#77776f]">{s.description}</p><div className="mt-9 overflow-hidden rounded-[24px] border border-[#e5e5dd] bg-white shadow-card"><Row title={s.starterTitle} description={s.starterDescription}><Segmented values={[3, 5, 8] as const} value={draft.starterMinutes} onChange={(starterMinutes) => update({ starterMinutes })} labels={{ 3: s.minutes.replace("{minutes}", "3"), 5: s.recommended.replace("{minutes}", "5"), 8: s.minutes.replace("{minutes}", "8") }} /></Row><Row title={s.assistTitle} description={s.assistDescription}><Segmented values={["allow", "never"] as const} value={draft.breathingAssist} onChange={(breathingAssist) => update({ breathingAssist })} labels={{ allow: s.allowBreathing, never: s.noBreathing }} /></Row></div><div className="mt-6 overflow-hidden rounded-[24px] border border-[#e5e5dd] bg-white shadow-card"><Row title={s.appearance} description={s.appearanceDescription}><Segmented values={["light", "dark"] as const} value={draft.theme} onChange={(theme) => update({ theme })} labels={{ light: s.light, dark: s.dark }} /></Row></div><div className="mt-6 rounded-[24px] border border-[#f0d8d4] bg-[#fff8f6] p-5 sm:p-6"><h2 className="font-semibold">{s.data}</h2><p className="mt-1 max-w-lg text-sm leading-relaxed text-[#806d69]">{s.dataDescription}</p><button onClick={() => { if (window.confirm(s.confirmClear)) { firstPilotCore.clearAll(); router.push("/"); router.refresh(); } }} className="mt-4 rounded-full border border-[#dca89e] px-4 py-2 text-sm font-medium text-[#9b4334]">{s.clear}</button></div><div className="mt-8 flex items-center justify-end gap-3"><span role="status" className="text-sm text-[#657149]">{notice}</span><button onClick={() => { data.updateSettings(draft); setNotice(s.saved); }} disabled={!changed} className="rounded-full bg-ink px-6 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45">{s.save}</button></div></section></AppShell>;
}
function Row({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="grid gap-4 border-b border-[#eeeeea] px-5 py-5 last:border-b-0 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center sm:gap-8 sm:px-6"><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 max-w-md text-sm leading-relaxed text-[#77776f]">{description}</p></div><div className="sm:justify-self-end">{children}</div></div>; }
function Segmented<T extends string | number>({ values, value, onChange, labels }: { values: readonly T[]; value: T; onChange: (value: T) => void; labels: Record<string, string> }) { return <div className="inline-flex max-w-full flex-wrap rounded-xl bg-[#f1f1ec] p-1">{values.map((item) => <button key={item} onClick={() => onChange(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-medium transition sm:text-sm ${value === item ? "bg-white text-ink shadow-sm" : "text-[#77776f] hover:text-ink"}`}>{labels[String(item)]}</button>)}</div>; }
