export const supportedLocales = ["zh", "en"] as const;
export type Locale = (typeof supportedLocales)[number];

const messages = {
  zh: {
    nav: { home: "首页", breathing: "呼吸训练", later: "稍后开始", history: "成长档案", settings: "设置", feedback: "反馈" }, language: "语言", switchLanguage: "切换语言", avatarAlt: "头像",
    home: { eyebrow: "你的 AI 行动向导", title: "今天想\n开始什么？", description: "帮助你从「想开始」，走到「已经开始」。不用规划全部，只处理眼前最大的阻碍。", taskLabel: "我想开始……", taskPlaceholder: "例如：做雅思听力、写代码、学习做饭", next: "下一步", back: "← 返回", stateEyebrow: "先不解决全部", stateTitle: "现在卡在哪？", stateDescription: "用自己的话说就好。例如：「我很累、很困，也有点烦。」我每次只带你走一步。", blockerLabel: "现在是什么情况？", blockerPlaceholder: "例如：我躺在床上刷手机，想做听力，但是一点都不想动。", preparing: "正在准备下一步…", start: "带我开始", error: "暂时无法准备这次开始，请重试。" },
    feedback: { eyebrow: "帮助 FirstPilot 变得更好", title: "给我们一点反馈", description: "你的每一条反馈都会帮助我们更好地理解：什么能真正帮你开始。", typeLabel: "这是什么反馈？", bug: "问题报告", feature: "功能建议", general: "其他想法", messageLabel: "发生了什么？", messagePlaceholder: "尽可能描述你当时的目标、看到的情况，以及你的期待。", quitLabel: "是什么差点让你放弃使用 FirstPilot？", quitPlaceholder: "例如：我不知道下一步该做什么、页面太慢、建议不符合我的情况……", contactLabel: "联系方式（可选）", contactPlaceholder: "邮箱；只在需要跟进时使用", satisfactionLabel: "你对 FirstPilot 的满意度", submit: "发送反馈", sending: "正在发送…", sent: "感谢你的反馈！我们已收到。", failed: "暂时无法发送反馈，请稍后重试。", required: "请先告诉我们发生了什么。", invalidContact: "请填写有效的邮箱地址或清空此项。", note: "无需登录。若留下联系方式，我们只会在需要跟进时联系你。" },
    breathing: { eyebrow: "调整状态", title: "呼吸训练", default: "（默认）", groups: "呼吸组数", group: "组", perGroup: "每组：", estimated: "预计 {seconds} 秒", enter: "进入准备", intro: "调整坐姿，放松肩膀，准备开始。", begin: "开始呼吸", prepare: "准备", start: "开始", return: "让注意力慢慢回到此刻。", assist: "呼吸辅助", completeTitle: "很好。", completeText: "呼吸已经完成。现在可以带着更稳定的节奏，开始下一步。", done: "完成", gentle: "慢一点，也没关系", inhale: "吸气", holdIn: "吸后停顿", exhale: "呼气", holdOut: "呼后停顿", ready: "完成", startMode: "开始学习", startModeDescription: "让自己安静下来，准备开始。", focusMode: "恢复专注", focusModeDescription: "暂停一下，把注意力带回眼前。", calmMode: "缓解焦虑", calmModeDescription: "放慢呼吸，给自己一点空间。", sleepMode: "睡前放松", sleepModeDescription: "让节奏慢下来，准备休息。", pattern: "吸气 {inhale} 秒 · 吸后停顿 {holdIn} 秒 · 呼气 {exhale} 秒 · 呼后停顿 {holdOut} 秒" },
    later: { eyebrow: "把它放在这里，等你准备好开始", title: "稍后开始", placeholder: "例如：第 52 章听力", add: "放进去", start: "开始", remove: "移除", removeLabel: "移除 {title}", empty: "暂时没有要稍后开始的事情。\n不用管理它们，只要在准备好时开始。", today: "今天加入", yesterday: "昨天加入", daysAgo: "{days} 天前加入" },
    history: { eyebrow: "回看每一次开始", title: "成长档案", actions: "行动次数", starts: "启动次数", completed: "完成动作", focus: "累计专注", breaths: "呼吸训练", times: "次", monthTrace: "本月行动痕迹", previousMonth: "上个月", nextMonth: "下个月", actionCount: "{count} 次行动", week: ["一", "二", "三", "四", "五", "六", "日"], monthSummary: "这个月，你已经让 {count} 件事情真正开始了。", today: "今天", todayStarts: "今日启动", todayCompleted: "今日完成", todayFocus: "今日专注", todayBreaths: "今日呼吸", todayActions: "今天的行动", noToday: "今天还没有行动记录。\n不用完成很多，先让一件事情开始。", fullHistory: "完整行动记录", historyLine: "行动 {actions} 次 · 专注 {focus} · 呼吸 {breaths} 次", empty: "还没有行动记录。完成一次启动后，它会被保存在这里。", focusLine: "专注 {focus}", calendarTitle: "{day} · {actions} 次行动", encouragementEmpty: "每一次开始都会被记录在这里。今天先完成一小段就好。", encouragementFocus: "你已经投入了 {focus}。这些时间都是给自己的积累。", encouragementStarts: "你已经启动了 {count} 次。你没有等待完美动力，而是一次次选择开始。", encouragementCompleted: "你已经完成了 {count} 个动作。小小的步骤正在变成真实的进步。" },
    settings: { title: "设置", description: "只保留会真正改变 FirstPilot 行为的选项。", starterTitle: "启动时长", starterDescription: "首次进入行动时的倒计时。建议从 5 分钟开始；页面文案与计时器会同步使用这个时长。", minutes: "{minutes} 分钟", recommended: "{minutes} 分钟 · 推荐", assistTitle: "启动辅助", assistDescription: "允许时，FirstPilot 只会在判断呼吸有助于移除当前阻碍时，才建议一次呼吸；不会把呼吸塞进固定流程。", allowBreathing: "允许呼吸辅助", noBreathing: "不使用呼吸", appearance: "外观", appearanceDescription: "切换浅色或深色界面。", light: "浅色", dark: "深色", data: "数据", dataDescription: "清除会永久移除本机的行动记录、成长档案与设置。", clear: "清除本地数据", confirmClear: "确定要清除所有本地数据吗？此操作无法撤销。", saved: "设置已保存，并会在下一次启动时生效。", save: "保存设置" },
    session: { ended: "这次启动已经结束。", home: "回到首页", resolving: "正在判断下一步…", resolvingText: "刚才那一步已经完成。我们只处理眼前最需要的一步。", oneThing: "现在只做这一件事", afterComplete: "完成后，我再带你走下一步。", didIt: "我做到了", noHelp: "这一步没有帮到我", ritual: "启动仪式", ready: "准备", breatheAssist: "呼吸辅助", firstStep: "很好，现在开始第一步。", firstFocus: "首次专注：{duration}", startAction: "开始行动", pause: "暂停", paused: "已暂停", resume: "继续专注", finishAction: "完成本次行动", freeText: "你已经进入状态了。按自己的节奏继续，不需要新的安排。", started: "你已经开始了", completedSegment: "又完成了一段", focusThisTime: "本次专注：{duration}", continue: "继续", endToday: "今天就到这里", summary: "今天到这里。", summaryText: "你完成了开始，也留下了一段真实的专注。", history: "成长档案", finish: "完成", praiseShort: "开始，比等待更重要。", praiseMedium: "节奏已经建立起来了。", praiseLong: "这是一段扎实的专注。", focusing: "正在专注" }
  },
  en: {
    nav: { home: "Home", breathing: "Breathe", later: "Later", history: "History", settings: "Settings", feedback: "Feedback" }, language: "Language", switchLanguage: "Switch language", avatarAlt: "Avatar",
    home: { eyebrow: "Your AI action guide", title: "What would you like\nto start today?", description: "Move from wanting to start to actually starting. You do not have to plan everything—just address the biggest obstacle in front of you.", taskLabel: "I want to start…", taskPlaceholder: "For example: IELTS listening, writing code, learning to cook", next: "Next", back: "← Back", stateEyebrow: "You do not need to solve everything", stateTitle: "Where are you stuck right now?", stateDescription: "Use your own words. For example: “I’m tired, distracted, and a little annoyed.” We’ll only take one step at a time.", blockerLabel: "What is going on right now?", blockerPlaceholder: "For example: I’m scrolling in bed. I want to study, but I can’t make myself move.", preparing: "Preparing your next step…", start: "Help me start", error: "We couldn't prepare this start. Please try again." },
    feedback: { eyebrow: "Help make FirstPilot better", title: "Share your feedback", description: "Every note helps us understand what genuinely helps you get started.", typeLabel: "What kind of feedback is this?", bug: "Bug report", feature: "Feature request", general: "Other thought", messageLabel: "What happened?", messagePlaceholder: "Describe what you were trying to do, what you saw, and what you expected.", quitLabel: "What's the one thing that almost made you stop using FirstPilot?", quitPlaceholder: "For example: I didn't know what to do next, the page was slow, or the suggestion didn't fit me…", contactLabel: "Contact details (optional)", contactPlaceholder: "Email; only used for follow-up", satisfactionLabel: "How satisfied are you with FirstPilot?", submit: "Send feedback", sending: "Sending…", sent: "Thank you—your feedback has been received.", failed: "We couldn't send your feedback. Please try again later.", required: "Please tell us what happened first.", invalidContact: "Enter a valid email address or leave this field empty.", note: "No sign-in required. If you leave contact details, we only use them for follow-up." },
    breathing: { eyebrow: "Reset your state", title: "Breathing practice", default: "(Default)", groups: "Breathing rounds", group: "round", perGroup: "Each round:", estimated: "About {seconds} seconds", enter: "Get ready", intro: "Adjust your posture, relax your shoulders, and get ready to begin.", begin: "Start breathing", prepare: "Prepare", start: "Start", return: "Bring your attention gently back to this moment.", assist: "Breathing assist", completeTitle: "Nice.", completeText: "Your breathing is complete. Take this steadier rhythm into your next step.", done: "Done", gentle: "Slower is okay", inhale: "Inhale", holdIn: "Hold", exhale: "Exhale", holdOut: "Rest", ready: "Done", startMode: "Start Learning", startModeDescription: "Settle in and get ready to begin.", focusMode: "Restore Focus", focusModeDescription: "Pause and bring your attention back.", calmMode: "Ease Anxiety", calmModeDescription: "Slow your breath and give yourself some space.", sleepMode: "Wind Down for Sleep", sleepModeDescription: "Slow the rhythm and get ready to rest.", pattern: "Inhale {inhale}s · Hold {holdIn}s · Exhale {exhale}s · Rest {holdOut}s" },
    later: { eyebrow: "Put it here until you're ready", title: "Start later", placeholder: "For example: Chapter 52 listening", add: "Save for later", start: "Start", remove: "Remove", removeLabel: "Remove {title}", empty: "Nothing is waiting here yet.\nYou don't have to manage it—just begin when you're ready.", today: "Added today", yesterday: "Added yesterday", daysAgo: "Added {days} days ago" },
    history: { eyebrow: "Look back at every start", title: "Your progress", actions: "Actions", starts: "Starts", completed: "Completed actions", focus: "Total focus", breaths: "Breathing", times: "times", monthTrace: "This month's starts", previousMonth: "Previous month", nextMonth: "Next month", actionCount: "{count} actions", week: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], monthSummary: "This month, you helped {count} things truly begin.", today: "Today", todayStarts: "Starts today", todayCompleted: "Completed today", todayFocus: "Focus today", todayBreaths: "Breathing today", todayActions: "Today's actions", noToday: "There are no action records today.\nYou don't need to do a lot—just let one thing begin.", fullHistory: "All activity", historyLine: "{actions} actions · {focus} focus · {breaths} breaths", empty: "No activity yet. Once you complete a start, it will be saved here.", focusLine: "Focus {focus}", calendarTitle: "{day} · {actions} actions", encouragementEmpty: "Every start is recorded here. Today, one small segment is enough.", encouragementFocus: "You've invested {focus}. That time is an investment in yourself.", encouragementStarts: "You've started {count} times. Instead of waiting for perfect motivation, you chose to begin again and again.", encouragementCompleted: "You've completed {count} actions. Small steps are becoming real progress." },
    settings: { title: "Settings", description: "Only options that genuinely change FirstPilot's behavior are kept here.", starterTitle: "Start duration", starterDescription: "The first-action countdown. We recommend five minutes; interface copy and the timer always use this duration together.", minutes: "{minutes} min", recommended: "{minutes} min · Recommended", assistTitle: "Start assist", assistDescription: "When enabled, FirstPilot suggests a breath only when it may help remove the current obstacle. Breathing is never forced into the flow.", allowBreathing: "Allow breathing", noBreathing: "No breathing", appearance: "Appearance", appearanceDescription: "Choose a light or dark interface.", light: "Light", dark: "Dark", data: "Data", dataDescription: "This permanently removes local activity, history, and settings from this device.", clear: "Clear local data", confirmClear: "Clear all local data? This cannot be undone.", saved: "Settings saved. They will apply to your next start.", save: "Save settings" },
    session: { ended: "This start has already ended.", home: "Back home", resolving: "Finding your next step…", resolvingText: "That step is done. We'll only handle the one thing that matters next.", oneThing: "Do just this one thing now", afterComplete: "When you're done, I'll guide your next step.", didIt: "I did it", noHelp: "This step didn't help", ritual: "Starting ritual", ready: "Get ready", breatheAssist: "Breathing assist", firstStep: "Nice. Now begin your first step.", firstFocus: "First focus: {duration}", startAction: "Start action", pause: "Pause", paused: "Paused", resume: "Resume focus", finishAction: "Finish this action", freeText: "You're in motion now. Continue at your own pace—no new plan needed.", started: "You've started", completedSegment: "Another segment complete", focusThisTime: "Focus this time: {duration}", continue: "Continue", endToday: "End for today", summary: "That's enough for today.", summaryText: "You started—and made room for a real stretch of focus.", history: "Your progress", finish: "Finish", praiseShort: "Starting matters more than waiting.", praiseMedium: "You've found a rhythm.", praiseLong: "That was a solid stretch of focus.", focusing: "Focusing" }
  }
} as const;

export type Messages = (typeof messages)[Locale];
export const getMessages = (locale: Locale) => messages[locale];
